# Generated by Django 5.2.1 on 2025-12-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
