# Generated by Django 5.2.1 on 2025-12-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_custom_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
