# Generated by Django 5.2.1 on 2025-12-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_custom_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='user', max_length=50),
        ),
    ]
