# Generated by Django 5.2.1 on 2025-12-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0005_alter_custom_user_groups_alter_custom_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
