# Generated by Django 5.2.1 on 2025-12-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_alter_custom_user_groups_alter_custom_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='STUDENT', max_length=50),
        ),
    ]
