# Generated by Django 5.2.1 on 2025-12-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0008_add_labs_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='labs',
        ),
    ]
