# Generated by Django 5.2.1 on 2025-12-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_remove_custom_user_labs'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
