# Generated by Django 5.2.1 on 2025-12-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='tags',
        ),
        migrations.AddField(
            model_name='lab',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='writeup_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='skills',
            field=models.JSONField(),
        ),
    ]
