# Generated by Django 5.2.1 on 2025-12-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0002_remove_lab_tags_lab_image_lab_writeup_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='author',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='content',
        ),
        migrations.AlterField(
            model_name='lab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_images/%Y/%m/%d/'),
        ),
    ]
