# Generated by Django 5.2.1 on 2025-12-23 15:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0003_remove_lab_author_remove_lab_content_alter_lab_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
