# Generated by Django 5.2.1 on 2025-12-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0005_lab_author_lab_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
